create table users
(
    id                 int8 generated by default as identity,
    created_at         timestamp default now(),
    updated_at         timestamp default now(),
    name               varchar(255),
    email              varchar(255),
    enabled            boolean   default true,
    password           varchar(255),
    current_profile_id int8,
    primary key (id)
);

create table users_roles
(
    user_id int8 not null,
    role    varchar(255),
    unique (user_id, role)
);

create table profiles
(
    id              int8 generated by default as identity,
    created_at      timestamp default now(),
    updated_at      timestamp default now(),
    name            varchar(255),
    bin             varchar(255),
    accountant      varchar(255),
    email           varchar(255),
    address_legal   varchar(255),
    address_real    varchar(255),
    phone           varchar(255),
    site            varchar(255),
    bank            varchar(255),
    iban            varchar(255),
    swift           varchar(255),
    kbe             int4,
    manager         varchar(255),
    reason          varchar(255),
    start_num       int4      default 1,
    subsidiary      varchar(255),
    vat_certificate varchar(255),
    vat_fare        int4,
    vat_type        int4,
    warehouse       varchar(255),
    user_id         int8 references users (id),
    primary key (id)
);

create table agent_profiles
(
    id            int8 generated by default as identity,
    created_at    timestamp    default now(),
    updated_at    timestamp    default now(),
    name          varchar(255) not null,
    bin           varchar(255),
    agent_type    varchar(255) default 'CLIENT',
    legal_type    varchar(255) default 'COMPANY',
    email         varchar(255),
    phone         varchar(255),
    address_legal varchar(255),
    address_real  varchar(255),
    site          varchar(255),
    bank          varchar(255),
    iban          varchar(255),
    swift         varchar(255),
    birth_date    date,
    comment       varchar(255),
    passport      varchar(255),
    position      varchar(255),
    profile_id    int8 references profiles (id),
    primary key (id)
);

create table bank_accounts
(
    profile_id       int8 references profiles (id),
    agent_profile_id int8 references agent_profiles (id),
    bank             varchar(255),
    iban             varchar(255),
    swift            varchar(255)
);

create table documents
(
    id                int8 generated by default as identity,
    created_at        timestamp default now(),
    updated_at        timestamp default now(),
    email             varchar(255),
    phone             varchar(255),
    address_legal     varchar(255),
    address_real      varchar(255),
    site              varchar(255),
    agent_name        varchar(255),
    akt_date          date,
    akt_num           int4,
    bank              varchar(255),
    iban              varchar(255),
    swift             varchar(255),
    bin               varchar(255),
    invoice_date      date,
    invoice_num       int4,
    payment_condition varchar(255),
    po_dover          varchar(255),
    reason            varchar(255),
    receipt_date      date,
    receipt_num       int4,
    status            int4,
    way_bill          varchar(255),
    profile_id        int8,
    primary key (id)
);

create table document_details
(
    id           int8 generated by default as identity,
    created_at   timestamp default now(),
    updated_at   timestamp default now(),
    name         varchar(255),
    measure_type varchar(255),
    no_vat_sum   int4,
    number       int4,
    price        int4,
    total_sum    int4,
    vat_price    int4,
    vat_sum      int4,
    doc_id       int8 references documents (id),
    primary key (id)
);

create table knp
(
    id          int8 generated by default as identity,
    created_at  timestamp default now(),
    updated_at  timestamp default now(),
    name        varchar(255),
    description varchar(255),
    primary key (id)
);

create table resources
(
    id           int8 generated by default as identity,
    created_at   timestamp,
    updated_at   timestamp,
    name         varchar(255),
    measure_unit varchar(255),
    price        int4 not null,
    remainder    int4 not null,
    type         int4,
    profile_id   int8 references profiles (id),
    primary key (id)
);

insert into users(name, email, password)
values ('Ruslan', 'ruslan@mail.ru', '{noop}123456'),
       ('Vladlena', 'vladlena@mail.ru', '{noop}123456');

insert into users_roles
values (1, 'ROLE_ADMIN'),
       (1, 'ROLE_USER'),
       (2, 'ROLE_USER');

insert into profiles(name, email, address_legal, address_real, phone, site,
                     bank, iban, swift, bin, kbe, user_id)
values ('ИП "Шакирова"', 'shakirova@mail.ru', 'ул. Тамерлановское шоссе 1а кв. 54', 'ул. Мангельдина д. 36, кв. 72',
        '7 702 3938222', 'www.arenda-shymkent.kz', 'АО "Каспи Банк"', '88888888888', 'KBCBA', '123456', 19, 1),
       ('Тоо "Сулпак"', 'sulpaka@mail.ru', 'ул. Тамерлановское шоссе 5б', 'ул. Мангельдина д. 36, кв. 72',
        '7 702 77777777', 'www.arenda-shymkent.kz', 'АО "Каспи Банк"', '88888888888', 'KBCBA', '123456', 19, 2);
insert into agent_profiles(name, bin, agent_type, legal_type, address_legal, bank, iban, swift, comment,
                           passport, position, profile_id)
values ('ТОО "Рога и Копыта', '5464656565', 'CLIENT', 'COMPANY', 'fddfdfdfd', 'dfdsfdsfds', '34343434', 'sdfdsfds',
        'comment', '4534645654', 'dfdsfdsfds', 1),
       ('ТОО "Рога', '5464656565', 'CLIENT', 'COMPANY', 'fddfdfdfd', 'dfdsfdsfds', '34343434', 'sdfdsfds',
        'comment', '4534645654', 'dfdsfdsfds', 1);